# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webInfo.Client'),
        ),
        migrations.AlterField(
            model_name='filequery',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webInfo.Engine'),
        ),
        migrations.AlterField(
            model_name='fileresults',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webInfo.Engine'),
        ),
    ]
