# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0004_auto_20170802_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='start_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='start_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='filequery',
            old_name='start_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='fileresults',
            old_name='start_date',
            new_name='create_date',
        ),
    ]
